import { createServiceClient } from "@/lib/supabase/service";
import { dealer } from "@/config/dealer";
import { sendCapiEvent, splitName, clientIpFrom } from "@/lib/meta/capi";

// General website leads: contact form + newsletter. Saves to site_leads and
// (if Resend is configured) emails the dealer. WhatsApp remains the primary
// channel; this is the backup capture so no enquiry is ever lost.

export const runtime = "nodejs";

type Payload = {
  channel?: string;
  name?: string;
  contact?: string;
  phone?: string;
  message?: string;
  subject?: string;
  stock_slug?: string;
  source?: string; // "Where did you hear about us?"
  page?: string; // pathname the lead came from
  company?: string; // honeypot
  // Meta Conversions API. event_id is generated by the browser and passed here
  // so the server-side event DEDUPLICATES against the browser one instead of
  // double-counting the same lead. See src/lib/meta/capi.ts.
  event_id?: string;
  vehicle_id?: number; // stock_id, so the event joins to the catalog row
  vehicle_price?: number;
  fbp?: string;
  fbc?: string;
};

const esc = (s = "") => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export async function POST(req: Request) {
  let body: Payload;
  try {
    body = (await req.json()) as Payload;
  } catch {
    return Response.json({ ok: false, error: "bad-request" }, { status: 400 });
  }

  // Honeypot: silently accept + drop.
  if (body.company) return Response.json({ ok: true });

  const channel = ["form", "whatsapp", "email", "newsletter", "poll", "interested", "finance", "autotrader"].includes(body.channel ?? "")
    ? (body.channel as string)
    : "form";

  // Build meta from whatever extras were sent (phone, attribution source, page).
  const meta: Record<string, string> = {};
  if (body.source) meta.source = body.source.slice(0, 100);
  if (body.phone) meta.phone = body.phone.slice(0, 60);
  if (body.page) meta.page = body.page.slice(0, 200);

  // Save the lead (best-effort; email is independent so nothing is lost).
  try {
    const supabase = createServiceClient();
    await supabase.from("site_leads").insert({
      stock_slug: body.stock_slug ?? null,
      name: body.name?.slice(0, 200) ?? null,
      contact: body.contact?.slice(0, 200) ?? null,
      channel,
      message: body.message?.slice(0, 4000) ?? body.subject?.slice(0, 200) ?? null,
      meta: Object.keys(meta).length ? meta : null,
    });
  } catch (e) {
    console.error("[lead] db insert failed:", e instanceof Error ? e.message : e);
  }

  // Mirror the conversion to Meta server-side, so it survives ad blockers and
  // iOS privacy. Deliberately NOT sent for the newsletter or the "how did you
  // hear about us" poll — neither is a sales conversion, and reporting them as
  // Leads would teach Meta to optimise toward the wrong action.
  //
  // ⚠️ Nothing from the finance application is ever sent. This route receives
  // only name/contact/phone; idNumber, dob, income and bank details live in the
  // separate finance flow and must never reach an ad platform.
  if (body.event_id && !["newsletter", "poll"].includes(channel)) {
    const { firstName, lastName } = splitName(body.name);
    // Awaited, not fire-and-forget: a serverless function can be frozen the
    // moment it responds, which would silently drop the request mid-flight.
    await sendCapiEvent({
      eventName: "Lead",
      eventId: body.event_id,
      eventSourceUrl: body.page ? `${dealer.siteUrl}${body.page}` : dealer.siteUrl,
      identity: {
        email: body.contact?.includes("@") ? body.contact : undefined,
        phone: body.phone ?? (body.contact?.includes("@") ? undefined : body.contact),
        firstName,
        lastName,
      },
      vehicle: body.vehicle_id
        ? { stock_id: body.vehicle_id, price: body.vehicle_price ?? null, title: body.message ?? null }
        : undefined,
      clientIpAddress: clientIpFrom(req.headers),
      clientUserAgent: req.headers.get("user-agent") ?? undefined,
      fbp: body.fbp,
      fbc: body.fbc,
    });
  }

  // Email the dealer if Resend is configured (added later).
  const apiKey = process.env.RESEND_API_KEY;
  if (apiKey) {
    const heading =
      channel === "newsletter" ? "New newsletter signup"
      : channel === "poll" ? "Website poll — where a visitor heard about us"
      : channel === "interested" ? "New vehicle interest"
      : channel === "finance" ? "New finance enquiry"
      : "New website enquiry";
    const html = `
      <div style="font-family:Arial,sans-serif;max-width:560px;margin:0 auto;color:#111">
        <h2 style="margin:0 0 4px">${heading}</h2>
        <p style="margin:0 0 16px;color:#666;font-size:13px">via ${esc(dealer.name)} website</p>
        <table style="width:100%;border-collapse:collapse;font-size:14px">
          ${body.name ? `<tr><td style="padding:6px 0;color:#888;width:110px">Name</td><td><strong>${esc(body.name)}</strong></td></tr>` : ""}
          ${body.contact ? `<tr><td style="padding:6px 0;color:#888">${body.phone ? "Email" : "Contact"}</td><td>${esc(body.contact)}</td></tr>` : ""}
          ${body.phone ? `<tr><td style="padding:6px 0;color:#888">Phone</td><td>${esc(body.phone)}</td></tr>` : ""}
          ${body.stock_slug ? `<tr><td style="padding:6px 0;color:#888">Vehicle</td><td>${esc(body.stock_slug)}</td></tr>` : ""}
          ${body.source ? `<tr><td style="padding:6px 0;color:#888">Heard via</td><td>${esc(body.source)}</td></tr>` : ""}
        </table>
        ${body.message ? `<div style="margin-top:16px;padding:14px 16px;background:#f5f5f3;border-radius:10px;font-size:14px">${esc(body.message)}</div>` : ""}
      </div>`;
    try {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          from: process.env.LEAD_FROM ?? `${dealer.name} <onboarding@resend.dev>`,
          to: (process.env.LEAD_TO ?? dealer.email).split(",").map((s) => s.trim()),
          ...(body.contact?.includes("@") ? { reply_to: body.contact } : {}),
          subject: `${heading}${body.name ? ` — ${body.name}` : ""}`,
          html,
        }),
      });
    } catch (e) {
      console.error("[lead] email failed:", e instanceof Error ? e.message : e);
    }
  }

  return Response.json({ ok: true });
}
